const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Spritefont2,
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Plugins.Flowchart,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Date,
		C3.Plugins.Dictionary,
		C3.Plugins.LocalStorage,
		C3.Plugins.Particles,
		C3.Plugins.TextBox,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Spritefont2.Acts.SetInstanceVar,
		C3.Plugins.Spritefont2.Exps.CharacterScale,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Cnds.LayerInteractive,
		C3.Plugins.Browser.Acts.Reload,
		C3.Plugins.Spritefont2.Cnds.IsVisible,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.Spritefont2.Acts.SetScale,
		C3.Plugins.System.Cnds.OnSaveComplete,
		C3.Plugins.System.Cnds.OnLoadComplete,
		C3.Plugins.System.Cnds.OnSaveFailed,
		C3.Plugins.System.Cnds.OnLoadFailed,
		C3.Plugins.Audio.Cnds.OnFadeEnded,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Exps.replace,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Date.Exps.GetYear,
		C3.Plugins.Date.Exps.Now,
		C3.Plugins.Date.Exps.GetMonth,
		C3.Plugins.Date.Exps.GetDay,
		C3.Plugins.Date.Exps.GetHours,
		C3.Plugins.Date.Exps.GetMinutes,
		C3.Plugins.Date.Exps.GetSeconds,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Dictionary.Cnds.CompareValue,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Spritefont2.Acts.SetEffectParam,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Spritefont2.Exps.BBoxLeft,
		C3.Plugins.Spritefont2.Exps.BBoxMidY,
		C3.Plugins.Spritefont2.Acts.SetOpacity,
		C3.Plugins.Spritefont2.Exps.Opacity,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Behaviors.Sin.Exps.Value,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Flowchart.Acts.StartFlowchart,
		C3.Plugins.Flowchart.Cnds.OnTaggedNodeChange,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.Flowchart.Exps.OutputValue,
		C3.Plugins.Flowchart.Cnds.OnAnyNodeChange,
		C3.Plugins.Flowchart.Exps.NodeTag,
		C3.Plugins.Flowchart.Cnds.ForEachOutput,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Flowchart.Exps.OutputCount,
		C3.Plugins.Spritefont2.Acts.TypewriterText,
		C3.Plugins.Flowchart.Exps.CurOutputValue,
		C3.Plugins.Flowchart.Exps.CurOutputName,
		C3.Plugins.Spritefont2.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Spritefont2.Exps.Width,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.TextBox.Exps.Width,
		C3.Plugins.TextBox.Acts.SetX,
		C3.Plugins.TextBox.Acts.SetTooltip,
		C3.Plugins.TextBox.Acts.SetMaxLength,
		C3.Plugins.TextBox.Acts.SetFocus,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Arr.Exps.CurY,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.TextBox.Exps.Count,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.Flowchart.Acts.GotoNextFlowchartNode,
		C3.Plugins.TextBox.Acts.Destroy,
		C3.Plugins.Spritefont2.Cnds.IsRunningTypewriterText,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Spritefont2.Acts.TypewriterFinish,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Spritefont2.Cnds.PickDistance,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Spritefont2.Cnds.CompareText,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Spritefont2.Acts.AppendText,
		C3.Plugins.Spritefont2.Acts.SetHeight,
		C3.Plugins.Spritefont2.Exps.TextHeight,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Spritefont2.Exps.Height,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Exps.find,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.right,
		C3.Plugins.Flowchart.Cnds.HasOutput,
		C3.Plugins.Flowchart.Cnds.CompareOutputValue,
		C3.Plugins.Spritefont2.Exps.Count,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Spritefont2.Cnds.CompareY,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Exps.fps,
		C3.Plugins.System.Exps.gpuutilisation,
		C3.Plugins.System.Exps.cpuutilisation,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Spritefont2.Exps.LayerName,
		C3.Plugins.Spritefont2.Exps.BBoxRight,
		C3.Plugins.Spritefont2.Exps.BBoxBottom,
		C3.Plugins.Spritefont2.Exps.BBoxTop,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Spritefont2.Acts.SetZ,
		C3.Plugins.Spritefont2.Exps.Z,
		C3.Plugins.Spritefont2.Acts.SetAngle,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.System.Exps.projectversion,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Anchor: 0},
	{Tween: 0},
	{CharacterSprite: 0},
	{Sine: 0},
	{percent: 0},
	{FontBackground: 0},
	{background: 0},
	{pickersprite: 0},
	{SliderCode: 0},
	{DragDrop: 0},
	{SliderKnov: 0},
	{MinVal: 0},
	{MaxVal: 0},
	{SliderBar: 0},
	{SystemBg: 0},
	{Logo: 0},
	{blackscreen: 0},
	{MenuSelecter: 0},
	{unnamed: 0},
	{AlertFont: 0},
	{IndexOutput: 0},
	{ChoiceFont: 0},
	{Scale: 0},
	{DialogueFont: 0},
	{NamerFont: 0},
	{ScriptPreview: 0},
	{Code: 0},
	{SystemFont: 0},
	{techspec: 0},
	{CODE: 0},
	{MainMenuFont: 0},
	{SystemFont2: 0},
	{FileSysFont: 0},
	{AJAX: 0},
	{DialogueArray: 0},
	{FlowchartController: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Audio: 0},
	{Browser: 0},
	{Date: 0},
	{Dictionary: 0},
	{LocalStorage: 0},
	{HeartParticles: 0},
	{HeartParticles2: 0},
	{HeartParticles3: 0},
	{HeartParticles4: 0},
	{Particles: 0},
	{Sex_cuadro: 0},
	{Fondo_Genero: 0},
	{White_heart: 0},
	{TextInput: 0},
	{Vol_MASTER: 0},
	{Vol_SFX: 0},
	{Vol_MUSIC: 0},
	{TextSpeed: 0},
	{TextSize: 0},
	{AudioFading: 0},
	{type: 0},
	{DialogueValue: 0},
	{TuNombre: 0},
	{PrefferedGender: 0},
	{ChoicesDistance: 0},
	{PassedString: 0},
	{Force: 0},
	{AnimationType: 0},
	{Alert_String: 0}
];

self.InstanceType = {
	Anchor: class extends self.ISpriteInstance {},
	CharacterSprite: class extends self.ISpriteInstance {},
	percent: class extends self.ISpriteInstance {},
	FontBackground: class extends self.ISpriteInstance {},
	background: class extends self.ISpriteInstance {},
	pickersprite: class extends self.ISpriteInstance {},
	SliderKnov: class extends self.ISpriteInstance {},
	SliderBar: class extends self.ISpriteInstance {},
	SystemBg: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	blackscreen: class extends self.ISpriteInstance {},
	MenuSelecter: class extends self.ISpriteInstance {},
	unnamed: class extends self.ISpriteInstance {},
	AlertFont: class extends self.ISpriteFontInstance {},
	ChoiceFont: class extends self.ISpriteFontInstance {},
	DialogueFont: class extends self.ISpriteFontInstance {},
	NamerFont: class extends self.ISpriteFontInstance {},
	ScriptPreview: class extends self.ISpriteFontInstance {},
	SystemFont: class extends self.ISpriteFontInstance {},
	techspec: class extends self.ISpriteFontInstance {},
	MainMenuFont: class extends self.ISpriteFontInstance {},
	SystemFont2: class extends self.ISpriteFontInstance {},
	FileSysFont: class extends self.ISpriteFontInstance {},
	AJAX: class extends self.IInstance {},
	DialogueArray: class extends self.IArrayInstance {},
	FlowchartController: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Date: class extends self.IInstance {},
	Dictionary: class extends self.IDictionaryInstance {},
	LocalStorage: class extends self.IInstance {},
	HeartParticles: class extends self.IParticlesInstance {},
	HeartParticles2: class extends self.IParticlesInstance {},
	HeartParticles3: class extends self.IParticlesInstance {},
	HeartParticles4: class extends self.IParticlesInstance {},
	Particles: class extends self.IParticlesInstance {},
	Sex_cuadro: class extends self.ISpriteInstance {},
	Fondo_Genero: class extends self.ISpriteInstance {},
	White_heart: class extends self.ISpriteInstance {},
	TextInput: class extends self.ITextInputInstance {}
}